version: "3.8"
services:
  db:
    image: postgres
    expose: 
      - 5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: BCAS_test
  web:
    build: .
    environment:
      DB_HOST: database
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678
      DB_PORT: 5432
      DB_DATABASE: BCAS_test
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure    
    links:
      - "db:database"